# syntax=docker/dockerfile:1

# ============================================================================
# CVLab -- single-container image: Next.js static frontend + FastAPI backend
# + the Pandoc/XeLaTeX toolchain used for PDF/DOCX/TXT export.
# ============================================================================

# ---------------------------------------------------------------------------
# Stage 1: build the frontend to static HTML (next.config.ts uses output:
# "export", so this emits frontend-next/out with no Node runtime needed).
# ---------------------------------------------------------------------------
FROM node:22-slim AS frontend

WORKDIR /build

# Install dependencies from the lockfile first so the layer caches across
# source-only changes.
COPY frontend-next/package.json frontend-next/package-lock.json ./
RUN npm ci

COPY frontend-next/ ./
# AGENTS.md/CLAUDE.md are regenerated by next; nothing here depends on them.
RUN npm run build


# ---------------------------------------------------------------------------
# Stage 2: runtime
# ---------------------------------------------------------------------------
FROM python:3.13-slim AS runtime

ENV PYTHONUNBUFFERED=1 \
    PYTHONDONTWRITEBYTECODE=1 \
    PYTHONPATH=/app/backend \
    DATA_DIR=/app/data \
    CV_DIR=/app/cv \
    EXPORTS_DIR=/app/exports \
    DEBIAN_FRONTEND=noninteractive

# Export toolchain:
#   pandoc                      -- markdown -> pdf/docx/txt
#   texlive-xetex + latex-extra -- XeLaTeX engine and the packages cv.latex
#                                  pulls in (titlesec, enumitem, ragged2e,
#                                  setspace, amssymb, fontspec)
#   fonts-liberation            -- the fonts templates/cv.latex selects
#   libmagic1                   -- python-magic, used for upload sniffing
#   zsh                         -- scripts/export.sh is a zsh script and uses
#                                  zsh-only syntax; without it the export
#                                  subprocess exits 127
RUN apt-get update && apt-get install -y --no-install-recommends \
        pandoc \
        zsh \
        texlive-xetex \
        texlive-latex-recommended \
        texlive-latex-extra \
        texlive-fonts-recommended \
        fonts-liberation \
        libmagic1 \
        curl \
        ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY backend/requirements.txt /app/backend/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /app/backend/requirements.txt

# Application code and the export pipeline's supporting assets.
COPY backend/ /app/backend/
COPY scripts/ /app/scripts/
COPY templates/ /app/templates/
COPY pandoc/ /app/pandoc/

# Static frontend. main.py mounts /app/static and serves _next/ from it.
COPY --from=frontend /build/out /app/static

RUN chmod +x /app/scripts/*.sh \
    && mkdir -p /app/data/cvs /app/data/config /app/data/exports /app/data/backups \
                /app/cv /app/exports/pdf /app/exports/docx /app/exports/txt

EXPOSE 8000

HEALTHCHECK --interval=30s --timeout=10s --start-period=20s --retries=3 \
    CMD curl -fsS http://localhost:8000/health || exit 1

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
